# Generated by Django 4.0.4 on 2022-05-04 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classId', models.IntegerField()),
                ('ClassName', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subId', models.IntegerField()),
                ('subName', models.CharField(max_length=64)),
            ],
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='eadd',
            new_name='eaddr',
        ),
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacherId', models.IntegerField()),
                ('teacherName', models.CharField(max_length=64)),
                ('teachersQual', models.TextField()),
                ('subId', models.ManyToManyField(blank=True, null=True, to='testapp.subjects')),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stdID', models.IntegerField()),
                ('studentName', models.CharField(max_length=64)),
                ('studentAddr', models.TextField()),
                ('studentGrade', models.FloatField()),
                ('classTeacherId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='testapp.teachers')),
                ('studentClass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.classtable')),
            ],
        ),
        migrations.AddField(
            model_name='classtable',
            name='teacherId',
            field=models.ManyToManyField(blank=True, null=True, to='testapp.teachers'),
        ),
    ]
