# Generated by Django 4.0.4 on 2022-05-04 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_classtable_subjects_rename_eadd_employee_eaddr_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classtable',
            old_name='ClassName',
            new_name='class_Name',
        ),
    ]
